scheduler_type: ddim_50_eps
inversion_type: dummy
model_name: stable-diffusion-v1-4
pipeline_type: ours
start_latent: inversion
verbose: false
edit_types: stylisation
guiders:
- name: cfg
  g_scale: 7.5
  kwargs:
    is_source_guidance: false
- name: self_attn_map_l2
  g_scale:
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 100000.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  kwargs: {}
- name: features_map_l2
  g_scale:
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 2.5
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  kwargs: {}
noise_rescaling_setup:
  type: range_other_on_cfg_norm
  init_setup:
  - 1.5
  - 1.5
